AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for DataLandscape lambdas

Parameters:
      IngestRedditFunctionName:
        Type: String
        Description: The name of the Ingest Reddit Lambda function.

Resources:
  IngestRedditFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref IngestRedditFunctionName
      CodeUri: ingest_reddit/
      Handler: ingest_reddit.lambda_handler
      Runtime: python3.13
      Description: Ingests data from Reddit API for specified subreddits and stores it in S3.
      Timeout: 300