PYPI_PROJECTS = [
    'deltalake',
    'pyiceberg',
    'avro',
    'pyarrow',
    'pyorc',
    'thrift',
    'protobuf',
    'kafka',
    'apache-flink',
    'confluent-kafka',
    'psycopg2',
    'mysql-connector-python',
    'pymongo',
    'pydruid',
    'couchbase',
    'clickhouse-connect',
    'redis',
    'neo4j',
    'pinecone',
    'weaviate-client',
    'qdrant-client',
    'chromadb',
    'duckdb',
    'dbt-core',
    'airbyte',
    'meltano',
    'apache-airflow',
    'dagster',
    'prefect',
    'mage-ai',
    'torch',
    'tensorflow',
    'keras',
    'xgboost',
    'lightgbm',
    'scikit-learn',
    'mlflow',
    'optuna',
    'wandb',
    'dvc',
    'neptune',
    'langchain',
    'llama-index',
    'litellm',
    'guidance',
    'dspy-ai',
    'lmql',
    'haystack-ai',
    'ollama',
    'openllm'
]

PROJECTS_SEARCH_TERMS = [
## Warehouse / Lakehouse
    'Databricks',
    'Snowflake',
    'BigQuery',
    'Starburst',
    'dremio',

### Analytics Engine
    'Spark',
    'Trino',
    'Presto',
    'Pinot',

### Formats
    'Delta Lake',
    'Iceberg',
    'Hudi',
    'parquet',
    'avro',
    'arrow',
    'orc',
    'thrift',
    'protobuf',

### Streaming
    'Kafka',
    'Flink',
    'Confluent',
    'Redpanda',
    'Striim',

### Databases
    'Postgres',
    'MySQL',
    'SQLServer',
    'DynamoDB',
    'CosmosDB',
    'MongoDB',
    'ScyllaDB',
    'Druid',
    'Couchbase',
    'CockroachDB',
    'MariaDB',
    'Cassandra',
    'ClickHouse',
    'redis',
    'Neo4j',
    'Pinecone',
    'Weaviate',
    'Qdrant',
    'chroma',
    'DuckDB',
    'SQLite',

### ETL/ELT
    'dbt',
    'Fivetran',
    'Airbyte',
    'Azure Data Factory',
    'AWS Glue',
    'Meltano',

### Orchestration
    'Airflow',
    'Astronomer',
    'Dagster',
    'Prefect',
    'Mage',

### Data Quality
    'Collibra',
    'Monte Carlo',
    'Soda',

### Machine Learning
    'PyTorch',
    'Tensorflow',
    'Keras',
    'XGBoost',
    'LightGBM',
    'Scikit-Learn',
    'Vertex AI',
    'Sagemaker',
    'Azure Machine Learning',
    'mlflow',
    'optuna',
    'Weights and Biases',
    'dvc',
    'Neptune',

### Generative AI
    'LangChain',
    'LlamaIndex',
    'LiteLLM',
    'DSPy',
    'LMQL',
    'Haystack',
    'Ollama',
    'llamacpp',
    'OpenLLM',
]