name: Deploy Lambda Function

on:
  push:
    branches:
      - data_landscape_migration

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LAMBDA_ROOT: scripts/lambda
      LAMBDA_CONFIG: lambdas.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV__LAMBDA_UPDATER__AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV__LAMBDA_UPDATER__AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Deploy all Lambda functions
        run: |
          CONFIG_FILE=$LAMBDA_ROOT/$LAMBDA_CONFIG
          for row in $(cat $CONFIG_FILE | jq -c '.[]'); do
            NAME=$(echo $row | jq -r '.name')
            FILE=$(echo $row | jq -r '.file')

            # Zip the Lambda function
            cd $LAMBDA_ROOT
            zip -r lambda_function.zip $FILE
            cd -

            # Upload the Lambda function
            aws lambda update-function-code \
              --function-name $NAME \
              --zip-file fileb://$LAMBDA_ROOT/lambda_function.zip \
              --publish
            
            # Update the Lambda configuration
            aws lambda update-function-configuration \
              --function-name $NAME \
              --handler $HANDLER
          done
