name: Lambda CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.13'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Create and activate virtual environment
        run: |
          uv venv .venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies and AWS SAM CLI
        run: |
          uv pip install -r lambdas/ingest_reddit/requirements.txt
          uv pip install -r lambdas/requirements-dev.txt
        shell: bash

      - name: Lint code
        run: make lint-lambdas
        shell: bash

      - name: Run Lambda tests
        run: |
          echo "Running Lambda tests..."
          make test-lambdas
        shell: bash
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV__LAMBDA_UPDATER__AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV__LAMBDA_UPDATER__AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV__AWS_REGION }}

      - name: Package Lambda function
        run: |
          sam package \
            --template-file lambdas/template.yaml \
            --output-template-file packaged-template.yaml \
            --s3-bucket ${{ secrets.DEV__LAMBDA_ARTIFACTS_S3_BUCKET }} \
            --s3-prefix sam-packages/${{ github.sha }}

      - name: Upload packaged template to S3
        run: |
          aws s3 cp packaged-template.yaml s3://${{ secrets.DEV__LAMBDA_ARTIFACTS_S3_BUCKET }}/sam-templates/${{ github.sha }}/packaged-template.yaml
        shell: bash